name: Build Lamnya OS

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install build tools
      run: |
        sudo apt update
        sudo apt install -y build-essential nasm xorriso grub-pc-bin grub-common qemu-system-x86

    - name: Build OS
      run: |
        make

    - name: Upload build
      uses: actions/upload-artifact@v4
      with:
        name: lamnya-build
        path: .
